#!/usr/bin/env bash
# Shared helpers for the install scripts: output, configuration, kubectl.
# Sourced by every scripts/*.sh; not meant to be run on its own.

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="${SMARTLINK_CONFIG:-$SCRIPTS_DIR/config.env}"

# --- Output ------------------------------------------------------------------
if [[ -t 1 ]]; then
  B=$'\e[1m' D=$'\e[2m' R=$'\e[0m' CYAN=$'\e[36m' GREEN=$'\e[32m' YELLOW=$'\e[33m' RED=$'\e[31m'
else
  B="" D="" R="" CYAN="" GREEN="" YELLOW="" RED=""
fi
_STEP=0

banner() {  # banner "02" "Argo CD" "description"
  # Inside install.sh the stage header already says where you are: one quiet line.
  if [[ -n "${SMARTLINK_ALL:-}" ]]; then printf '\n    %s── %s · %s%s\n' "$D" "$1" "$2" "$R"; return 0; fi
  local line="━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  printf '\n%s%s%s\n' "$CYAN" "$line" "$R"
  printf '  %sSMARTLINK%s %s·%s %s%s%s  %s%s%s\n' "$B" "$R" "$D" "$R" "$CYAN" "$1" "$R" "$B" "$2" "$R"
  [[ -n "${3:-}" ]] && printf '  %s%s%s\n' "$D" "$3" "$R"
  printf '%s%s%s\n' "$CYAN" "$line" "$R"
}
step()  { _STEP=$((_STEP + 1)); printf '\n%s[%d]%s %s%s%s\n' "$CYAN" "$_STEP" "$R" "$B" "$*" "$R"; }
ok()    { printf '    %s✔%s %s\n' "$GREEN" "$R" "$*"; }
info()  { printf '    %s%s%s\n' "$D" "$*" "$R"; }
warn()  { printf '    %s⚠ %s%s\n' "$YELLOW" "$*" "$R"; }
fail()  { printf '\n    %s✖ %s%s\n\n' "$RED" "$*" "$R" >&2; exit 1; }
next()  {  # not needed inside install.sh: it moves on by itself
  [[ -n "${SMARTLINK_ALL:-}" ]] && return 0
  printf '\n%s━━ Done.%s Next: %s%s%s\n\n' "$GREEN" "$R" "$B" "$*" "$R"
}

# need_sudo "what for" — asks for the password once, with a clear prompt
# (sudo does not ask again afterwards).
# The password is read by sudo itself (sudo -v), never by this script: it is not
# in any variable, file or log. sudo only caches "already authenticated" for a
# few minutes, the usual sudo behavior.
need_sudo() {
  sudo -n true 2>/dev/null && return 0
  local who="your user on this machine"
  [[ "$(uname -s)" == Darwin ]] && who="your Mac (the login one)"
  info "Administrator rights needed $1 (it changes the system, not just this folder)."
  info "sudo asks for the password itself: this script never sees or stores it."
  sudo -v -p "    ${YELLOW}🔑${R} Password for ${who}: " || fail "Administrator rights are required to continue"
}

# wait_for "description" <seconds> command...  — retries every 3 s
wait_for() {
  local desc="$1" timeout="$2"; shift 2
  local end=$((SECONDS + timeout))
  printf '    %s… %s%s' "$D" "$desc" "$R"
  until "$@" >/dev/null 2>&1; do
    ((SECONDS < end)) || { printf '\n'; fail "Timed out waiting for: $desc"; }
    printf '%s.%s' "$D" "$R"; sleep 3
  done
  printf '\r    %s✔%s %s\033[K\n' "$GREEN" "$R" "$desc"
}

# --- Configuration -------------------------------------------------------------
# Non-secret values live in scripts/config.env (git-ignored). Secrets are
# always asked interactively and never written to disk.
load_config() {  # created empty the first time; the scripts fill it in
  # The VM scripts install system software: never on your computer.
  [[ "$(uname -s)" == Linux ]] || fail "This runs on the VM (Linux), not on your computer. Use ./scripts/install.sh (on macOS it creates the VM)"
  [[ -f "$CONFIG_FILE" ]] || printf '# Generated by scripts/: NON-secret values of this installation.\n' > "$CONFIG_FILE"
  # shellcheck source=/dev/null
  source "$CONFIG_FILE"
}
require() {  # require VAR "what it is for"
  [[ -n "${!1:-}" ]] || fail "Missing $1 in scripts/config.env ($2)"
}
ask_value() {  # ask_value VAR "question" — if VAR is empty, asks for it and saves it
  local _v
  [[ -n "${!1:-}" ]] && return 0
  printf '    %s?%s %s: ' "$CYAN" "$R" "$2" >/dev/tty
  read -r _v </dev/tty
  [[ -n "$_v" ]] || fail "Empty value"
  save_config "$1" "$_v"
  printf -v "$1" '%s' "$_v"
}
ask_secret() {  # ask_secret "Text" ["where it ends up"] → prints the value (no echo on screen)
  # The prompt goes straight to the terminal: visible even if output is redirected.
  # The script never echoes it, never writes it to config.env or a log, and never
  # passes it as a command-line argument. Where it does end up is said in $2.
  local v
  printf '    %s(hidden while you type · %s)%s\n' "$D" "${2:-kept in memory for this run only}" "$R" >/dev/tty
  printf '    %s🔑%s %s: ' "$YELLOW" "$R" "$1" >/dev/tty
  read -rs v </dev/tty; printf '\n' >/dev/tty
  [[ -n "$v" ]] || fail "Empty value"
  printf '%s' "$v"
}
save_config() {  # save_config VAR value — adds or replaces it in config.env
  local key="$1" val="$2"
  if grep -q "^${key}=" "$CONFIG_FILE"; then
    sed -i.bak "s|^${key}=.*|${key}=${val}|" "$CONFIG_FILE" && rm -f "$CONFIG_FILE.bak"
  else
    printf '%s=%s\n' "$key" "$val" >> "$CONFIG_FILE"
  fi
}

# --- Guided install (install.sh) ---------------------------------------------------
stage() {  # stage N TOTAL "title" — one stage of the guided install
  printf '\n%s┏━ %s/%s ━━ %s%s%s\n' "$CYAN" "$1" "$2" "$B" "$3" "$R"
}
todo() { printf '    %s›%s %s\n' "$CYAN" "$R" "$*"; }      # something you have to do
link() { printf '      %s%s%s\n' "$B" "$*" "$R"; }           # URL to open
pause() { local _; printf '    %s%s%s ' "$D" "${1:-Press Enter to continue…}" "$R" >/dev/tty; read -r _ </dev/tty; }

# cf_token — the Cloudflare token (D1 Edit). install.sh asks for it once and passes
# it to 03 and 04 through the environment; a script run on its own asks for it.
cf_token() {
  if [[ -n "${CLOUDFLARE_API_TOKEN:-}" ]]; then printf '%s' "$CLOUDFLARE_API_TOKEN"
  else ask_secret "Cloudflare token (D1 Edit)" "stored in Vault for the backend; nowhere else on this VM"
  fi
}

# version KEY — reads a bootstrap version (k3s, helm) from deploy/root/values.yaml.
# Chart versions are not here: each is in deploy/components/<name>/Chart.yaml.
version() {
  local v; v="$(awk -v k="$1" '$1 == k":" {print $2; exit}' "$SCRIPTS_DIR/../deploy/root/values.yaml")"
  [[ -n "$v" ]] || fail "Version '$1' not found in deploy/root/values.yaml"
  printf '%s' "$v"
}

# repo_slug — GitHub "<owner>/<repo>": REPO_SLUG from config.env if set (install.sh
# saves it once you confirm it), otherwise this clone's origin remote.
repo_slug() {
  [[ -n "${REPO_SLUG:-}" ]] && { printf '%s' "$REPO_SLUG"; return 0; }
  local u; u="$(git -C "$SCRIPTS_DIR/.." remote get-url origin 2>/dev/null)" || fail "No origin remote found: run the scripts from a clone of the repo"
  u="${u%.git}"; u="${u#git@github.com:}"; u="${u#ssh://git@github.com/}"; u="${u#https://github.com/}"
  [[ "$u" =~ ^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$ ]] || fail "The origin remote is not a GitHub repo: $u"
  printf '%s' "$u"
}

# --- Cluster -----------------------------------------------------------------------
k() { sudo k3s kubectl "$@"; }

# install_shortcuts — "k" (kubectl) and "v" (vault CLI inside the pod) in every new
# shell of this VM, so nobody has to paste them. Idempotent.
install_shortcuts() {
  local rc="$HOME/.bashrc"
  grep -qF "# >>> smartlink shortcuts >>>" "$rc" 2>/dev/null && return 0
  cat >> "$rc" <<'EOF'

# >>> smartlink shortcuts >>>
k() { sudo k3s kubectl "$@"; }                                    # kubectl
v() { sudo k3s kubectl -n vault exec -i vault-0 -- vault "$@"; }  # vault CLI, inside the pod
# <<< smartlink shortcuts <<<
EOF
}
